### ISSUE TITLE
 No translation file found for domain

### ISSUE THREAD

**Issue by ftyers** [Codepoints/unidump#2]
```
fran@ipek:~/source/unidump$ python3 setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from unidump.cli import description, epilog
  File "/home/fran/source/unidump/unidump/cli.py", line 14, in <module>
    tl = gettext.translation('unidump', localedir=dirname(__file__)+'/locale')
  File "/usr/lib/python3.7/gettext.py", line 539, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'unidump'
```

The problem is that my locale is: `ca_ES.utf8` and in locales there is only `de`. The program could fallback to English if the locale is not found.

**Comment by Boldewyn** [comment]
Hello, and thank you for reporting the issue!

You were completely right, the fallback option for Gettext was missing. This should be fixed now.
